import './globals.css'
import './icons.css'
import { ThemeProvider } from '@/components/services/Theme-Provider'
import { RobotoFont, Lobster } from './fonts/fonts'
import { Suspense } from 'react'
import Loading from './Loading'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${RobotoFont.variable} ${Lobster.variable} antialiased min-h-screen overflow-x-hidden`}>
        <ThemeProvider attribute='class' defaultTheme={'system'} enableSystem={true} disableTransitionOnChange={false}>
          <Suspense fallback={<Loading />}>
            {children}
          </Suspense>
        </ThemeProvider>
      </body>
    </html>
  )
}
